keys:
  - &x123 age1vnrrkyd9h8d5u8l07nghetuv2mt5wwu5krhln5sp8ztycquzxc9qu5n877
  - &system_xnix age1cuhquw0nsjm2nsuggezdkmxsj92p5vc97jtjmskmpwxdh50k5djs3xusfc
  - &system_hetznix age10qcnqa522q8txznv59n02zh3jgw6a9nwlsjj9eezxxvrykvkkskqtd8d4n
  - &system_wgnix age13re5npdkf29lch3mp5hm48yed3d0fkc0s3yu0wzu0x9jxl9nn4yseeq78a
  - &system_wgnix-vm age1aj73mlk837xqmt2ahtjv09k78fyudv7t9h623fmtq5vn93029qmq2y3ua8
  - &mba age1qsykrrtcjsmhw9zst5r52vzpkdj7mxp66c0has02vcf7an230p0s07hhpn
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
  - path_regex: ^system/xnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_xnix
  - path_regex: ^system/xnix/users/.+/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_xnix
  - path_regex: ^system/nixquisite/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
  - path_regex: ^system/hetznix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_hetznix
  - path_regex: ^users/x-xnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
  - path_regex: ^system/wgnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_wgnix
  - path_regex: ^system/wgnix-vm/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_wgnix-vm
