keys:
  - &x123 age1vnrrkyd9h8d5u8l07nghetuv2mt5wwu5krhln5sp8ztycquzxc9qu5n877
  - &system_xnix age1cuhquw0nsjm2nsuggezdkmxsj92p5vc97jtjmskmpwxdh50k5djs3xusfc
  - &system_nixium age1lmafgcalluhdzyjmfty98c9l4w23pvddw68tulyxf03lu25yh9rq2s48k3
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
        - *x123
  - path_regex: ^system/xnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *system_xnix
  - path_regex: ^system/nixium/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *system_nixium
  - path_regex: ^users/x-xnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
