keys:
  - &x123 age1vnrrkyd9h8d5u8l07nghetuv2mt5wwu5krhln5sp8ztycquzxc9qu5n877
  - &system_xnix age1cuhquw0nsjm2nsuggezdkmxsj92p5vc97jtjmskmpwxdh50k5djs3xusfc
  - &system_nixium age192p08wwdswnxajx80ec7ugsasn6x7aa0gvrj5myzllww09hvsgwqsy5fj2
  - &system_hetznix age10qcnqa522q8txznv59n02zh3jgw6a9nwlsjj9eezxxvrykvkkskqtd8d4n
  - &mba age1qsykrrtcjsmhw9zst5r52vzpkdj7mxp66c0has02vcf7an230p0s07hhpn
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
  - path_regex: ^system/xnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_xnix
  - path_regex: ^system/nixium/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_nixium
  - path_regex: ^system/nixquisite/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
  - path_regex: ^system/hetznix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
        - *system_hetznix
  - path_regex: ^users/x-xnix/[^/]+\.yaml$
    key_groups:
      - age:
        - *x123
        - *mba
